kuma_server_url: http://networkbot:3001
kuma_heartbeat_interval: 300
kuma_retry_interval: 60
kuma_max_retries: 2
kuma_admin_username: '{{ vault_kuma_admin_username }}'
kuma_admin_password: '{{ vault_kuma_admin_password }}'
