kuma_server_url: http://networkbot:3001
kuma_heartbeat_interval: 300
kuma_retry_interval: 60
kuma_max_retries: 2
kuma_heartbeat_script_path: '{{ ansible_env.HOME }}/kuma-heartbeat.sh'
kuma_log_file: '{{ ansible_env.HOME }}/kuma-heartbeat.log'
kuma_admin_username: admin
kuma_admin_password: '{{ vault_kuma_admin_password | default(''admin'') }}'
