- name: Deploy Kuma Push Monitor and Heartbeat
  hosts: '{{ target_host }}'
  gather_facts: true
  vars:
    kuma_url: '{{ kuma_server_url }}'
    monitor_name: '{{ ansible_hostname }}'
    heartbeat_interval: 300
    max_retries: 2
    retry_interval: 60
    heartbeat_script_path: /usr/local/bin/kuma-heartbeat.sh
    cron_schedule: '*/5 * * * *'
  tasks:
  - name: Create push monitor in Kuma
    lucasheld.uptime_kuma.monitor:
      api_url: '{{ kuma_url }}'
      api_token: '{{ kuma_auth_token }}'
      name: '{{ monitor_name }}'
      type: push
      interval: '{{ heartbeat_interval }}'
      retryInterval: '{{ retry_interval }}'
      maxretries: '{{ max_retries }}'
      notificationIDList: '{{ notification_ids | default([]) }}'
      state: present
    register: monitor_response
    delegate_to: localhost
    run_once: true
  - name: Extract push token from response
    set_fact:
      push_token: '{{ monitor_response.monitor.pushToken }}'
    when: monitor_response.monitor.pushToken is defined
  - name: Fail if push token not received
    fail:
      msg: Failed to create monitor or extract push token
    when: push_token is not defined
  - name: Create heartbeat script
    template:
      src: heartbeat.sh.j2
      dest: '{{ heartbeat_script_path }}'
      mode: '0755'
      owner: root
      group: root
    become: true
  - name: Install cron job for heartbeat
    cron:
      name: Kuma heartbeat for {{ monitor_name }}
      minute: '*/5'
      job: '{{ heartbeat_script_path }}'
      state: present
    become: true
  - name: Test heartbeat immediately
    command: '{{ heartbeat_script_path }}'
    register: heartbeat_test
    become: true
  - name: Display heartbeat test result
    debug:
      msg: 'Heartbeat test result: {{ heartbeat_test.rc }}'
  - name: Display monitor status
    debug:
      msg: 'Monitor "{{ monitor_name }}" created successfully with push token: {{ push_token }}'
