- name: Deploy Kuma monitoring to all hosts
  hosts: kuma_monitors:synology_nas:proxmox_hosts
  become: false
  become_method: sudo
  become_flags: -n
  roles:
  - role: ../roles/internal/kuma-monitoring
  tags:
  - monitoring
  - kuma
